import "./globals.css";
import { Metadata } from "next";
import "/public/assets/css/custom.css";
import 'react-toastify/dist/ReactToastify.css';
import { Providers } from "@/redux/provider";

export const metadata: Metadata = {
  title: "Eminence Jewellery Admin",
  description: "Eminence Jewellery administration panel.",
};

export default function RootLayout({children}:{children: React.ReactNode}) {
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex, follow" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <link rel="icon" href="/assets/img/logo/eminence-mark-v2.png" />
      </head>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
