const category = [
  {
    _id: "63a9a063d283e1a02a2a6af9",
    parent: "Rings",
    img: "/assets/img/product/product-1.jpg",
    children: ["rings"],
    status: "Show",
    products: [],
  },
  {
    _id: "63a9a063d283e1a02a2a6afd",
    parent: "Necklaces",
    img: "/assets/img/product/details/big/product-details-big-1.jpg",
    children: ["necklaces"],
    status: "Show",
    products: [],
  },
  {
    _id: "63a9a063d283e1a02a2a6afb",
    parent: "Earrings",
    img: "/assets/img/eminence/products/eminence-earrings.png",
    children: ["earrings"],
    status: "Show",
    products: [],
  },
  {
    _id: "63a9a063d283e1a02a2a6afc",
    parent: "Bracelets",
    img: "/assets/img/product/product-8.jpg",
    children: ["bracelets"],
    status: "Show",
    products: [],
  },
  {
    _id: "63a9a063d283e1a02a2a6afa",
    parent: "Bangles",
    img: "/assets/img/product/category/product-cat-1.jpg",
    children: ["bangles"],
    status: "Show",
    products: [],
  },
  {
    _id: "63a9a063d283e1a02a2a6afe",
    parent: "Anklets",
    img: "/assets/img/product/category/product-cat-2.jpg",
    children: ["anklets"],
    status: "Show",
    products: [],
  },
  {
    _id: "63a9a063d283e1a02a2a6af8",
    parent: "Jewellery Sets",
    img: "/assets/img/product/details/description/product-description-1.jpg",
    children: ["jewellery-sets"],
    status: "Show",
    products: [],
  },
  {
    _id: "63a9a063d283e1a02a2a6aff",
    parent: "Diamonds",
    img: "/assets/img/product/details/big/product-details-big-4.jpg",
    children: ["diamonds"],
    status: "Show",
    products: [],
  },
  {
    _id: "63a9a063d283e1a02a2a6b00",
    parent: "Bridal Jewellery",
    img: "/assets/img/eminence/bridal-jewellery-hero.jpg",
    children: ["bridal-jewellery"],
    status: "Show",
    products: [],
  },
  {
    _id: "63a9a063d283e1a02a2a6b02",
    parent: "Breslate",
    img: "/assets/img/breslate/breslate.png",
    children: ["breslate"],
    status: "Show",
    products: [],
  },
  {
    _id: "63a9a063d283e1a02a2a6b01",
    parent: "Bespoke Atelier",
    img: "/assets/img/product/details/description/product-description-3.jpg",
    children: ["bespoke-atelier"],
    status: "Show",
    products: [],
  },
];

module.exports = category;
