const image = {
  ring: "/assets/img/eminence/products/ChatGPT Image Jun 13, 2026, 11_11_02 PM.png",
  bridal: "/assets/img/eminence/bridal-jewellery-hero.jpg",
  breslate: "/assets/img/breslate/breslate.png",
  earrings: "/assets/img/eminence/products/eminence-earrings.png",
  chain: "/assets/img/eminence/products/ChatGPT Image Jun 13, 2026, 11_05_49 PM (3).png",
};

const orders = [
  {
    user: "62c827b5a427b63741da9175",
    cart: [
      {
        _id: "64b78b80cf982ba18a26b13b",
        sku: "EM-RNG-001",
        title: "Celeste Diamond Halo Ring",
        parent: "Rings",
        children: "diamond-rings",
        tags: ["rings", "diamond", "engagement"],
        image: image.ring,
        originalPrice: 235000,
        price: 211500,
        discount: 10,
        brand: "Celeste Diamonds",
        unit: "1 piece",
        quantity: 18,
        colors: ["white-gold", "diamond"],
        type: "Jewellery",
        itemInfo: "top-rated",
        status: "active",
        orderQuantity: 1,
      },
    ],
    name: "Richard E. Romero",
    address: "Gulberg",
    email: "richard@gmail.com",
    contact: "123456789",
    city: "Lahore",
    country: "Pakistan",
    zipCode: "54000",
    subTotal: 211500,
    shippingCost: 1500,
    discount: 0,
    totalAmount: 213000,
    shippingOption: "insured-courier",
    status: "pending",
  },
  {
    user: "62cc0791d511b304aecdfbf2",
    cart: [
      {
        _id: "64b78b80cf982ba18a26b131",
        sku: "NB-BRD-008",
        title: "Noor Bridal Statement Set",
        parent: "Bridal Jewellery",
        children: "bridal-sets",
        tags: ["bridal", "jewellery-set", "wedding"],
        image: image.bridal,
        originalPrice: 620000,
        price: 575000,
        discount: 7,
        brand: "Noor Bridal",
        unit: "1 set",
        quantity: 8,
        colors: ["yellow-gold", "ruby", "kundan"],
        type: "Jewellery",
        itemInfo: "top-rated",
        status: "active",
        orderQuantity: 1,
      },
      {
        _id: "64b78b80cf982ba18a26b12c",
        sku: "EM-ERG-003",
        title: "Eminence Pearl Drop Earrings",
        parent: "Earrings",
        children: "drop-earrings",
        tags: ["earrings", "pearls", "evening"],
        image: image.earrings,
        originalPrice: 145000,
        price: 132000,
        discount: 9,
        brand: "Eminence Signature",
        unit: "Pair",
        quantity: 30,
        colors: ["pearl", "yellow-gold"],
        type: "Jewellery",
        itemInfo: "latest-product",
        status: "active",
        orderQuantity: 1,
      },
    ],
    name: "Brain H. Landry",
    address: "Clifton",
    email: "brain@gmail.com",
    contact: "123456789",
    city: "Karachi",
    country: "Pakistan",
    zipCode: "75600",
    subTotal: 707000,
    shippingCost: 2500,
    discount: 35000,
    totalAmount: 674500,
    shippingOption: "insured-courier",
    status: "processing",
  },
  {
    user: "62d2bbd22e63b40520194f1b",
    cart: [
      {
        _id: "64b78b80cf982ba18a26b12d",
        sku: "BR-BRS-004",
        title: "Breslate Signature Gold Bracelet",
        parent: "Breslate",
        children: "statement-breslate",
        tags: ["breslate", "bracelet", "gold"],
        image: image.breslate,
        originalPrice: 165000,
        price: 149500,
        discount: 9,
        brand: "Breslate Atelier",
        unit: "1 piece",
        quantity: 21,
        colors: ["yellow-gold"],
        type: "Jewellery",
        itemInfo: "top-rated",
        status: "active",
        orderQuantity: 2,
      },
      {
        _id: "64b78b80cf982ba18a26b130",
        sku: "AU-CHN-007",
        title: "Aurelia Classic Gold Chain",
        parent: "Chains",
        children: "gold-chains",
        tags: ["chains", "gold", "classic"],
        image: image.chain,
        originalPrice: 98000,
        price: 89500,
        discount: 9,
        brand: "Aurelia Gold",
        unit: "1 piece",
        quantity: 36,
        colors: ["yellow-gold"],
        type: "Jewellery",
        itemInfo: "best-selling",
        status: "active",
        orderQuantity: 1,
      },
    ],
    name: "Thomas",
    address: "Blue Area",
    email: "thomas@gmail.com",
    contact: "123456789",
    city: "Islamabad",
    country: "Pakistan",
    zipCode: "44000",
    subTotal: 388500,
    shippingCost: 2000,
    discount: 18000,
    totalAmount: 372500,
    shippingOption: "insured-courier",
    status: "delivered",
  },
];

module.exports = orders;
