const productImages = {
  ring: "/assets/img/eminence/products/ChatGPT Image Jun 13, 2026, 11_11_02 PM.png",
  necklace: "/assets/img/eminence/products/ChatGPT Image Jun 13, 2026, 11_05_48 PM (1).png",
  earrings: "/assets/img/eminence/products/eminence-earrings.png",
  breslate: "/assets/img/breslate/breslate.png",
  bangle: "/assets/img/eminence/products/ChatGPT Image Jun 13, 2026, 11_05_50 PM (4).png",
  pendant: "/assets/img/eminence/products/ChatGPT Image Jun 13, 2026, 11_05_49 PM (2).png",
  chain: "/assets/img/eminence/products/ChatGPT Image Jun 13, 2026, 11_05_49 PM (3).png",
  bridal: "/assets/img/eminence/bridal-jewellery-hero.jpg",
  bracelet: "/assets/img/eminence/products/ChatGPT Image Jun 13, 2026, 11_05_50 PM (5).png",
  bespoke: "/assets/img/eminence/products/anja.png",
  anklet: "/assets/img/eminence/products/ChatGPT Image Jun 9, 2026, 01_23_31 AM.png",
  set: "/assets/img/eminence/bridal-jewellery-3d.png",
};

const categories = {
  rings: { name: "Rings", id: "63a9a063d283e1a02a2a6af9" },
  necklaces: { name: "Necklaces", id: "63a9a063d283e1a02a2a6afd" },
  earrings: { name: "Earrings", id: "63a9a063d283e1a02a2a6afb" },
  bracelets: { name: "Bracelets", id: "63a9a063d283e1a02a2a6afc" },
  bangles: { name: "Bangles", id: "63a9a063d283e1a02a2a6afa" },
  pendants: { name: "Pendants", id: "63a9a063d283e1a02a2a6b03" },
  chains: { name: "Chains", id: "63a9a063d283e1a02a2a6b04" },
  sets: { name: "Jewellery Sets", id: "63a9a063d283e1a02a2a6af8" },
  diamonds: { name: "Diamonds", id: "63a9a063d283e1a02a2a6aff" },
  bridal: { name: "Bridal Jewellery", id: "63a9a063d283e1a02a2a6b00" },
  breslate: { name: "Breslate", id: "63a9a063d283e1a02a2a6b02" },
  bespoke: { name: "Bespoke Atelier", id: "63a9a063d283e1a02a2a6b01" },
};

const brands = {
  signature: { name: "Eminence Signature", id: "64b7735fae177ed4d70fb5c3" },
  aurelia: { name: "Aurelia Gold", id: "64b7735fae177ed4d70fb5c7" },
  celeste: { name: "Celeste Diamonds", id: "64b7735fae177ed4d70fb5c6" },
  noor: { name: "Noor Bridal", id: "64b7735fae177ed4d70fb5c4" },
  breslate: { name: "Breslate Atelier", id: "64b7735fae177ed4d70fb5c5" },
};

const products = [
  {
    _id: "64b78b80cf982ba18a26b13b",
    sku: "EM-RNG-001",
    title: "Celeste Diamond Halo Ring",
    parent: "Rings",
    children: "diamond-rings",
    tags: ["rings", "diamond", "engagement"],
    image: productImages.ring,
    originalPrice: 235000,
    price: 211500,
    discount: 10,
    relatedImages: [productImages.ring, productImages.pendant, productImages.earrings],
    description:
      "A brilliant halo ring with a polished gold band, diamond accents, and a refined luxury finish.",
    brand: brands.celeste,
    category: categories.rings,
    unit: "1 piece",
    quantity: 18,
    colors: ["white-gold", "diamond"],
    type: "Jewellery",
    itemInfo: "top-rated",
    status: "active",
  },
  {
    _id: "64b78b80cf982ba18a26b13e",
    sku: "EM-NCK-002",
    title: "Aurelia Layered Gold Necklace",
    parent: "Necklaces",
    children: "gold-necklaces",
    tags: ["necklaces", "gold", "layered"],
    image: productImages.necklace,
    originalPrice: 185000,
    price: 169000,
    discount: 9,
    relatedImages: [productImages.necklace, productImages.chain, productImages.pendant],
    description:
      "An elegant layered necklace in warm gold, designed for evening styling and bridal trousseaus.",
    brand: brands.aurelia,
    category: categories.necklaces,
    unit: "1 piece",
    quantity: 24,
    colors: ["yellow-gold"],
    type: "Jewellery",
    itemInfo: "best-selling",
    status: "active",
  },
  {
    _id: "64b78b80cf982ba18a26b12c",
    sku: "EM-ERG-003",
    title: "Eminence Pearl Drop Earrings",
    parent: "Earrings",
    children: "drop-earrings",
    tags: ["earrings", "pearls", "evening"],
    image: productImages.earrings,
    originalPrice: 145000,
    price: 132000,
    discount: 9,
    relatedImages: [productImages.earrings, productImages.necklace, productImages.set],
    description:
      "Pearl drop earrings with a luminous finish, made to pair beautifully with bridal and occasion wear.",
    brand: brands.signature,
    category: categories.earrings,
    unit: "Pair",
    quantity: 30,
    colors: ["pearl", "yellow-gold"],
    type: "Jewellery",
    itemInfo: "latest-product",
    status: "active",
  },
  {
    _id: "64b78b80cf982ba18a26b12d",
    sku: "BR-BRS-004",
    title: "Breslate Signature Gold Bracelet",
    parent: "Breslate",
    children: "statement-breslate",
    tags: ["breslate", "bracelet", "gold"],
    image: productImages.breslate,
    originalPrice: 165000,
    price: 149500,
    discount: 9,
    relatedImages: [productImages.breslate, productImages.bracelet, productImages.bangle],
    description:
      "A signature breslate piece with sculpted gold detailing and a polished luxury presentation.",
    brand: brands.breslate,
    category: categories.breslate,
    unit: "1 piece",
    quantity: 21,
    colors: ["yellow-gold"],
    type: "Jewellery",
    itemInfo: "top-rated",
    status: "active",
  },
  {
    _id: "64b78b80cf982ba18a26b12e",
    sku: "AU-BNG-005",
    title: "Aurelia Diamond Edge Bangles",
    parent: "Bangles",
    children: "diamond-bangles",
    tags: ["bangles", "diamond", "gold"],
    image: productImages.bangle,
    originalPrice: 275000,
    price: 248000,
    discount: 10,
    relatedImages: [productImages.bangle, productImages.bracelet, productImages.ring],
    description:
      "A matched bangle pair with crisp diamond edging, made for formal styling and gift sets.",
    brand: brands.aurelia,
    category: categories.bangles,
    unit: "Pair",
    quantity: 14,
    colors: ["yellow-gold", "diamond"],
    type: "Jewellery",
    itemInfo: "best-selling",
    status: "active",
  },
  {
    _id: "64b78b80cf982ba18a26b12f",
    sku: "EM-PDN-006",
    title: "Eminence Solitaire Pendant",
    parent: "Pendants",
    children: "diamond-pendants",
    tags: ["pendants", "solitaire", "diamond"],
    image: productImages.pendant,
    originalPrice: 125000,
    price: 115000,
    discount: 8,
    relatedImages: [productImages.pendant, productImages.chain, productImages.ring],
    description:
      "A solitaire pendant with clean lines and a brilliant center stone for a refined everyday look.",
    brand: brands.signature,
    category: categories.pendants,
    unit: "1 piece",
    quantity: 28,
    colors: ["white-gold", "diamond"],
    type: "Jewellery",
    itemInfo: "latest-product",
    status: "active",
  },
  {
    _id: "64b78b80cf982ba18a26b130",
    sku: "AU-CHN-007",
    title: "Aurelia Classic Gold Chain",
    parent: "Chains",
    children: "gold-chains",
    tags: ["chains", "gold", "classic"],
    image: productImages.chain,
    originalPrice: 98000,
    price: 89500,
    discount: 9,
    relatedImages: [productImages.chain, productImages.pendant, productImages.necklace],
    description:
      "A classic gold chain with a smooth finish, made for pendants or refined standalone styling.",
    brand: brands.aurelia,
    category: categories.chains,
    unit: "1 piece",
    quantity: 36,
    colors: ["yellow-gold"],
    type: "Jewellery",
    itemInfo: "best-selling",
    status: "active",
  },
  {
    _id: "64b78b80cf982ba18a26b131",
    sku: "NB-BRD-008",
    title: "Noor Bridal Statement Set",
    parent: "Bridal Jewellery",
    children: "bridal-sets",
    tags: ["bridal", "jewellery-set", "wedding"],
    image: productImages.bridal,
    originalPrice: 620000,
    price: 575000,
    discount: 7,
    relatedImages: [productImages.bridal, productImages.set, productImages.earrings],
    description:
      "A complete bridal set with layered detailing, statement presence, and heirloom-quality finishing.",
    brand: brands.noor,
    category: categories.bridal,
    unit: "1 set",
    quantity: 8,
    colors: ["yellow-gold", "ruby", "kundan"],
    type: "Jewellery",
    itemInfo: "top-rated",
    status: "active",
  },
  {
    _id: "64b78b80cf982ba18a26b132",
    sku: "CL-BRC-009",
    title: "Celeste Diamond Tennis Bracelet",
    parent: "Bracelets",
    children: "tennis-bracelets",
    tags: ["bracelets", "diamond", "tennis-bracelet"],
    image: productImages.bracelet,
    originalPrice: 340000,
    price: 319000,
    discount: 6,
    relatedImages: [productImages.bracelet, productImages.bangle, productImages.ring],
    description:
      "A diamond tennis bracelet with balanced sparkle, secure clasping, and a graceful silhouette.",
    brand: brands.celeste,
    category: categories.bracelets,
    unit: "1 piece",
    quantity: 16,
    colors: ["white-gold", "diamond"],
    type: "Jewellery",
    itemInfo: "best-selling",
    status: "active",
  },
  {
    _id: "64b78b80cf982ba18a26b133",
    sku: "NB-BSP-010",
    title: "Noor Bespoke Heirloom Suite",
    parent: "Bespoke Atelier",
    children: "custom-jewellery",
    tags: ["bespoke", "custom", "heirloom"],
    image: productImages.bespoke,
    originalPrice: 780000,
    price: 735000,
    discount: 6,
    relatedImages: [productImages.bespoke, productImages.bridal, productImages.set],
    description:
      "A made-to-order jewellery suite for clients who want a custom heirloom with atelier finishing.",
    brand: brands.noor,
    category: categories.bespoke,
    unit: "1 set",
    quantity: 5,
    colors: ["yellow-gold", "emerald", "diamond"],
    type: "Jewellery",
    itemInfo: "latest-product",
    status: "active",
  },
  {
    _id: "64b78b80cf982ba18a26b134",
    sku: "BR-ANK-011",
    title: "Breslate Delicate Gold Anklet",
    parent: "Breslate",
    children: "gold-breslate",
    tags: ["breslate", "anklet", "gold"],
    image: productImages.anklet,
    originalPrice: 74000,
    price: 68000,
    discount: 8,
    relatedImages: [productImages.anklet, productImages.chain, productImages.breslate],
    description:
      "A delicate gold anklet from the breslate collection with fine links and subtle shine.",
    brand: brands.breslate,
    category: categories.breslate,
    unit: "1 piece",
    quantity: 27,
    colors: ["yellow-gold"],
    type: "Jewellery",
    itemInfo: "latest-product",
    status: "active",
  },
  {
    _id: "64b78b80cf982ba18a26b135",
    sku: "EM-SET-012",
    title: "Eminence Diamond Jewellery Set",
    parent: "Jewellery Sets",
    children: "diamond-sets",
    tags: ["jewellery-set", "diamond", "occasion"],
    image: productImages.set,
    originalPrice: 485000,
    price: 449000,
    discount: 7,
    relatedImages: [productImages.set, productImages.earrings, productImages.necklace],
    description:
      "A coordinated diamond jewellery set with necklace and earrings for formal occasions.",
    brand: brands.signature,
    category: categories.sets,
    unit: "1 set",
    quantity: 10,
    colors: ["white-gold", "diamond"],
    type: "Jewellery",
    itemInfo: "top-rated",
    status: "active",
  },
];

module.exports = products;
